
# Variables
SCRIPT=brun_vcs.sh

# Default target
all: run

# Run the script
run:
	bash $(SCRIPT)

# Clean up
clean:
	rm -rf AN.DB c_model.o csrc simv simv.daidir test.vcd simv.log ucli.key vc_hdrs.h 
.PHONY: all run clean
